# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ARvAo-q61bAQYYQA2KEVrOR4NXVYWq4r
"""

import pandas as pd

# Load the student career dataset
try:
    df_students = pd.read_excel('/content/student_career_dataset_10000.xlsx')
    print("Successfully loaded 'student_career_dataset_10000.xlsx'")
except FileNotFoundError:
    print("Error: 'student_career_dataset_10000.xlsx' not found. Please ensure the file is in the correct directory.")
    df_students = pd.DataFrame() # Create an empty DataFrame to avoid errors later

# Display the first 5 rows of the DataFrame
if not df_students.empty:
    print("\nFirst 5 rows of the dataset:")
    display(df_students.head())

    # Display basic information about the DataFrame (columns and data types)
    print("\nInformation about the dataset:")
    display(df_students.info())

import matplotlib.pyplot as plt
import seaborn as sns

if not df_students.empty:
    plt.figure(figsize=(14, 7))
    sns.boxplot(x='Favorite_Subject', y='GPA', data=df_students)
    plt.title('GPA Distribution by Favorite Subject')
    plt.xlabel('Favorite Subject')
    plt.ylabel('GPA')
    plt.xticks(rotation=45, ha='right') # Rotate x-axis labels for better readability
    plt.grid(axis='y', linestyle='--', alpha=0.7)
    plt.tight_layout() # Adjust layout to prevent labels from overlapping
    plt.show()
else:
    print("Cannot plot GPA by Favorite Subject: DataFrame is empty.")

if not df_students.empty:
    avg_gpa_by_subject = df_students.groupby('Favorite_Subject')['GPA'].mean().sort_values(ascending=False)
    print("\nAverage GPA by Favorite Subject:")
    display(avg_gpa_by_subject)
else:
    print("Cannot calculate average GPA by Favorite Subject: DataFrame is empty.")

"""### Impact of 'Leadership' and 'Teamwork' on GPA

Let's visualize the distribution of GPA based on a student's 'Leadership' and 'Teamwork' levels to see if these factors play a role in academic performance.
"""

if not df_students.empty:
    plt.figure(figsize=(12, 6))
    sns.boxplot(x='Leadership', y='GPA', data=df_students, palette='viridis')
    plt.title('GPA Distribution by Leadership Level')
    plt.xlabel('Leadership Level')
    plt.ylabel('GPA')
    plt.grid(axis='y', linestyle='--', alpha=0.7)
    plt.show()
else:
    print("Cannot plot GPA by Leadership Level: DataFrame is empty.")

if not df_students.empty:
    plt.figure(figsize=(12, 6))
    sns.boxplot(x='Teamwork', y='GPA', data=df_students, palette='plasma')
    plt.title('GPA Distribution by Teamwork Level')
    plt.xlabel('Teamwork Level')
    plt.ylabel('GPA')
    plt.grid(axis='y', linestyle='--', alpha=0.7)
    plt.show()
else:
    print("Cannot plot GPA by Teamwork Level: DataFrame is empty.")

"""### Correlation Heatmap of Numerical Features

To understand the relationships between all numerical variables, let's generate a heatmap of their correlations. A heatmap uses colors to represent the strength and direction of the correlation between two variables.
"""

import matplotlib.pyplot as plt
import seaborn as sns

if not df_students.empty:
    # Select only numerical columns for correlation calculation
    numerical_cols = df_students.select_dtypes(include=['int64', 'float64']).columns

    # Calculate the correlation matrix for all numerical columns
    correlation_matrix_all = df_students[numerical_cols].corr()

    plt.figure(figsize=(10, 8)) # Adjust figure size for better readability
    sns.heatmap(correlation_matrix_all, annot=True, cmap='coolwarm', fmt=".2f", linewidths=.5)
    plt.title('Correlation Heatmap of All Numerical Features')
    plt.xticks(rotation=45, ha='right') # Rotate x-axis labels
    plt.yticks(rotation=0) # Ensure y-axis labels are horizontal
    plt.tight_layout() # Adjust layout to prevent labels from being cut off
    plt.show()
else:
    print("Cannot create correlation heatmap: DataFrame is empty.")

import matplotlib.pyplot as plt
import seaborn as sns

if not df_students.empty:
    plt.figure(figsize=(10, 6))
    sns.histplot(df_students['GPA'], bins=20, kde=True)
    plt.title('Distribution of GPA Scores')
    plt.xlabel('GPA')
    plt.ylabel('Number of Students')
    plt.grid(True)
    plt.show()
else:
    print("Cannot plot GPA distribution: DataFrame is empty.")

if not df_students.empty:
    # Select only numerical columns for correlation calculation, including GPA
    numerical_cols = df_students.select_dtypes(include=['int64', 'float64']).columns

    # Calculate the correlation matrix
    correlation_matrix = df_students[numerical_cols].corr()

    # Display correlations with 'GPA'
    print("\nCorrelations with GPA:")
    display(correlation_matrix['GPA'].sort_values(ascending=False))

    # Visualize the correlation matrix using a heatmap
    plt.figure(figsize=(8, 6))
    sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f")
    plt.title('Correlation Matrix of Numerical Features')
    plt.show()
else:
    print("Cannot calculate correlations: DataFrame is empty.")

import matplotlib.pyplot as plt
import seaborn as sns

# Check if df_students is not empty before plotting
if not df_students.empty:
    plt.figure(figsize=(10, 6))
    sns.scatterplot(x='Study_Hours', y='GPA', data=df_students)
    plt.title('Study Hours vs. GPA')
    plt.xlabel('Study Hours')
    plt.ylabel('GPA')
    plt.grid(True)
    plt.show()
else:
    print("Cannot plot: DataFrame is empty.")

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

if not df_students.empty:
    # Define features (X) and target (y)
    X = df_students[['Study_Hours']]
    y = df_students['GPA']

    # Split the data into training and testing sets (80% train, 20% test)
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    print("Data split into training and testing sets successfully!")
    print(f"Training data samples: {X_train.shape[0]}")
    print(f"Testing data samples: {X_test.shape[0]}")

    # Initialize and train the Linear Regression model
    model = LinearRegression()
    model.fit(X_train, y_train)

    print("\nLinear Regression model trained successfully!")
    print(f"Model Intercept: {model.intercept_:.2f}")
    print(f"Model Coefficient (Study_Hours): {model.coef_[0]:.2f}")

    # Make predictions on the test set
    y_pred = model.predict(X_test)

    # Evaluate the model
    mse = mean_squared_error(y_test, y_pred)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_test, y_pred)

    print(f"\nMean Squared Error (MSE): {mse:.2f}")
    print(f"Root Mean Squared Error (RMSE): {rmse:.2f}")
    print(f"R-squared (R2) Score: {r2:.2f}")

    # Plotting the regression line
    plt.figure(figsize=(10, 6))
    sns.scatterplot(x='Study_Hours', y='GPA', data=df_students, label='Actual Data', alpha=0.6)
    plt.plot(X_test, y_pred, color='red', linewidth=2, label='Regression Line')
    plt.title('Study Hours vs. GPA with Regression Line')
    plt.xlabel('Study Hours')
    plt.ylabel('GPA')
    plt.grid(True)
    plt.legend()
    plt.show()

    # Example prediction for a new student
    new_study_hours = np.array([[5]]) # A student studies for 5 hours
    predicted_gpa = model.predict(new_study_hours)
    print(f"\nPredicted GPA for a student studying {new_study_hours[0][0]} hours: {predicted_gpa[0]:.2f}")

else:
    print("Cannot build model: DataFrame is empty.")

from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

if not df_students.empty:
    # Identify numerical and categorical features
    numerical_features = ['Study_Hours', 'Sleep_Hours'] # Added Sleep_Hours as another numerical feature
    categorical_features = df_students.select_dtypes(include=['object']).columns.tolist()

    # Remove 'Career' from categorical features if it's not meant to be a predictor
    if 'Career' in categorical_features:
        categorical_features.remove('Career')

    # Define the preprocessing steps
    preprocessor = ColumnTransformer(
        transformers=[
            ('num', 'passthrough', numerical_features),
            ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features)
        ])

    # Create a pipeline with preprocessing and a RandomForestRegressor model
    # RandomForestRegressor is a more powerful model than simple Linear Regression for complex relationships
    model_improved = Pipeline(steps=[
        ('preprocessor', preprocessor),
        ('regressor', RandomForestRegressor(n_estimators=100, random_state=42))
    ])

    # Define features (X_improved) and target (y)
    # We'll use all relevant features this time
    X_improved = df_students[numerical_features + categorical_features]
    y_improved = df_students['GPA']

    # Split the data into training and testing sets
    X_train_improved, X_test_improved, y_train_improved, y_test_improved = train_test_split(
        X_improved, y_improved, test_size=0.2, random_state=42)

    print("\nPreparing to train an improved model with more features...")

    # Train the improved model
    model_improved.fit(X_train_improved, y_train_improved)

    print("Improved model trained successfully!")

    # Make predictions on the test set
    y_pred_improved = model_improved.predict(X_test_improved)

    # Evaluate the improved model
    mse_improved = mean_squared_error(y_test_improved, y_pred_improved)
    rmse_improved = np.sqrt(mse_improved)
    r2_improved = r2_score(y_test_improved, y_pred_improved)

    print(f"\nImproved Model Mean Squared Error (MSE): {mse_improved:.2f}")
    print(f"Improved Model Root Mean Squared Error (RMSE): {rmse_improved:.2f}")
    print(f"Improved Model R-squared (R2) Score: {r2_improved:.2f}")

    # Example prediction for a new student with multiple features
    # Let's create a hypothetical student's data
    new_student_data = pd.DataFrame([{
        'Study_Hours': 5,
        'Sleep_Hours': 8,
        'Personality': 'Extrovert',
        'Favorite_Subject': 'Mathematics',
        'Morning_Night': 'Morning',
        'Leadership': 'High',
        'Teamwork': 'Medium',
        'Creativity': 'High',
        'Communication': 'High',
        'Problem_Solving': 'High',
        'Critical_Thinking': 'High',
        'Analytical_Skills': 'High',
        'Empathy': 'Medium',
        'Attention_to_Detail': 'High',
        'Coding_Interest': 'Yes',
        'Math_Interest': 'Yes',
        'Science_Interest': 'Yes',
        'Business_Interest': 'No',
        'Art_Interest': 'No',
        'Writing_Interest': 'No',
        'Public_Speaking': 'Yes',
        'Research_Interest': 'Yes',
        'Outdoor_Preference': 'Indoor',
        'Preferred_Work': 'Team',
        'Volunteer': 'Yes',
        'Sports': 'Yes'
    }])

    predicted_gpa_new_student = model_improved.predict(new_student_data[numerical_features + categorical_features])
    print(f"\nPredicted GPA for a new hypothetical student: {predicted_gpa_new_student[0]:.2f}")

else:
    print("Cannot build improved model: DataFrame is empty.")